# Generated by Django 4.2.9 on 2025-06-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_message'),
    ]

    operations = [
    ]
